apiVersion: v1
kind: Namespace
metadata:
  name: near
---
apiVersion: v1
kind: Service
metadata:
  name: near-service
spec:
  type: NodePort
  ports:
  - port: 3030
    protocol: TCP
    name: near-status
  - port: 24567
    protocol: TCP
    name: near-node
  selector:
    app: nearup
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: near-deployment
  namespace: near
  labels:
    app: nearup
spec:
  replicas: 1
  strategy:
    type: Recreate # if not, the lock on database file from other pod will prevent app from starting
  selector:
    matchLabels:
      app: nearup
  template:
    metadata:
      labels:
        app: nearup
    spec:
      imagePullSecrets:
        - name: dc-n99wd
      volumes:
        - name: near-data
          persistentVolumeClaim:
            claimName: near-data-claim
      containers:
        - name: nearup
          image: gielve/main:1.14.0-beta.2
          env:
            - name: ACCOUNT_ID
              value: gielve.stakehouse.betanet
            - name: NETWORK
              value: betanet
          imagePullPolicy: Always
          ports:
          - containerPort: 24567
          - containerPort: 3030
          livenessProbe:
            httpGet:
              path: /status
              port: 3030
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 600
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /status
              port: 3030
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 2
          volumeMounts:
            - mountPath: "/.near/"
              name: near-data